var currentMap = "Underwater";

markerSet(-160, 712, "Red Shard", hiddenIcon, currentMap);
markerSet(-176, 690, "HP UP", hiddenIcon, currentMap);
markerSet(-212, 674, "Heart Scale", hiddenIcon, currentMap);
markerSet(-182, 652, "Star Piece", hiddenIcon, currentMap);
markerSet(-200, 625, "Big Pearl", hiddenIcon, currentMap);
markerSet(-159, 623, "Stardust", hiddenIcon, currentMap);
markerSet(-159, 601, "Ultra Ball", hiddenIcon, currentMap);
markerSet(-157, 590, "Heart Scale", hiddenIcon, currentMap);
markerSet(-175, 572, "Yellow Shard", hiddenIcon, currentMap);
markerSet(-176, 570, "Pearl", hiddenIcon, currentMap);
markerSet(-179, 571, "Iron", hiddenIcon, currentMap);
markerSet(-217, 569, "Blue Shard", hiddenIcon, currentMap);
markerSet(-239, 678, "Protein", hiddenIcon, currentMap);
markerSet(-238, 709, "Pearl", hiddenIcon, currentMap);
markerSet(-114, 624, "Big Pearl", hiddenIcon, currentMap);
markerSet(-124, 630, "Heart Scale", hiddenIcon, currentMap);
markerSet(-94, 626, "Pearl", hiddenIcon, currentMap);
markerSet(-96, 605, "Heart Scale", hiddenIcon, currentMap);
markerSet(-65, 602, "Calcium", hiddenIcon, currentMap);
markerSet(-100, 574, "Green Shard", hiddenIcon, currentMap);
markerSet(-111, 602, "Carbos", hiddenIcon, currentMap);